import type { CommonMistakeQuestion, StudentSubmission } from './types'

export const TEMPLATE_3D_LABELS: Record<string, { label: string; icon: string; desc: string }> = {
  '3D_CUBE_CLUSTER': {
    label: 'Cụm Lập Phương Không Gian',
    icon: '🧊',
    desc: 'Xoay tự do 360°, bóc tách từng tầng để đếm khối ẩn',
  },
  'GRID_PATH_MAZE': {
    label: 'Mê Cung Lưới Toạ Độ',
    icon: '🧭',
    desc: 'Mô phỏng 10 lộ trình ngắn nhất với thuật toán cộng dồn',
  },
  'INTERACTIVE_CLOCK': {
    label: 'Đồng Hồ Kim Tương Tác',
    icon: '⏰',
    desc: 'Kéo kim giờ/phút theo thời gian thực và đo góc KaTeX',
  },
  '3D_BALANCE_SCALE': {
    label: 'Cân Đĩa Thăng Bằng 3D',
    icon: '⚖️',
    desc: 'Thêm bớt quả cân trực quan để giải phương trình ẩn số',
  },
  'MATCHSTICK_FIGURE': {
    label: 'Mô Hình Que Diêm',
    icon: '🥢',
    desc: 'Kéo thả đổi vị trí que diêm để kiểm tra tính đúng sai',
  },
  'SHADED_AREA_FRACTION': {
    label: 'Phân Số & Diện Tích Tô Màu',
    icon: '📐',
    desc: 'Tô màu các phần bánh/hình tròn để hình thành phân số',
  },
  'NET_CUBE_FOLDING': {
    label: 'Trải Khối & Gấp Hình Lập Phương',
    icon: '📦',
    desc: 'Animation gấp phẳng 6 mặt thành khối lập phương 3D',
  },
}

export const INITIAL_SUBMISSIONS: StudentSubmission[] = [
  {
    id: 'sub-01',
    studentName: 'Nguyễn An Nhiên',
    studentGrade: 1,
    examId: 'asmo-math-g1-2020-r1',
    examTitle: 'Đề Thi Olympic Toán ASMO Lớp 1 (School Level - 2020)',
    subject: 'math',
    score: 92,
    totalPoints: 100,
    scorePct: 92,
    isPassed: true,
    durationMinutes: 42,
    submittedAt: '12 phút trước',
  },
  {
    id: 'sub-02',
    studentName: 'Trần Minh Khang',
    studentGrade: 2,
    examId: 'asmo-math-g2-2020-r1',
    examTitle: 'Đề Thi Olympic Toán ASMO Lớp 2 (School Level - 2020)',
    subject: 'math',
    score: 84,
    totalPoints: 100,
    scorePct: 84,
    isPassed: true,
    durationMinutes: 48,
    submittedAt: '35 phút trước',
  },
  {
    id: 'sub-03',
    studentName: 'Lê Bảo Nam',
    studentGrade: 3,
    examId: 'asmo-math-g3-2021-r1',
    examTitle: 'Đề Thi Olympic Toán ASMO Lớp 3 (School Level - 2021)',
    subject: 'math',
    score: 52,
    totalPoints: 100,
    scorePct: 52,
    isPassed: false,
    durationMinutes: 58,
    submittedAt: '1 giờ trước',
  },
  {
    id: 'sub-04',
    studentName: 'Vũ Phương Linh',
    studentGrade: 5,
    examId: 'asmo-sci-l2-2022-r1',
    examTitle: 'Đề Thi Olympic Khoa Học ASMO Cấp Độ 2 (2022)',
    subject: 'science',
    score: 76,
    totalPoints: 100,
    scorePct: 76,
    isPassed: true,
    durationMinutes: 38,
    submittedAt: '2 giờ trước',
  },
  {
    id: 'sub-05',
    studentName: 'Hoàng Đức Anh',
    studentGrade: 4,
    examId: 'asmo-eng-l2-2022-r1',
    examTitle: 'Đề Thi Olympic Tiếng Anh ASMO Cấp Độ 2 (2022)',
    subject: 'english',
    score: 88,
    totalPoints: 100,
    scorePct: 88,
    isPassed: true,
    durationMinutes: 45,
    submittedAt: '3 giờ trước',
  },
  {
    id: 'sub-06',
    studentName: 'Đỗ Quỳnh Anh',
    studentGrade: 1,
    examId: 'asmo-math-g1-2020-r1',
    examTitle: 'Đề Thi Olympic Toán ASMO Lớp 1 (School Level - 2020)',
    subject: 'math',
    score: 48,
    totalPoints: 100,
    scorePct: 48,
    isPassed: false,
    durationMinutes: 60,
    submittedAt: '5 giờ trước',
  },
]

export const INITIAL_COMMON_MISTAKES: CommonMistakeQuestion[] = [
  {
    questionId: 'asmo-math-g1-2020-r1-q03',
    examCode: 'ASMO-MATH-G01-2020-R1',
    topicName: 'Đọc Mặt Đồng Hồ & Tính Góc Kim',
    questionText: 'Tính góc tạo bởi kim giờ và kim phút lúc 3 giờ 30 phút.',
    wrongRatePct: 68,
    wrongAttemptsCount: 142,
    commonPitfall: 'Học sinh thường quên kim giờ đã di chuyển được 15 độ khi kim phút chỉ số 6, dẫn đến chọn nhầm 90° thay vì 75°.',
  },
  {
    questionId: 'asmo-math-g1-2020-r1-q05',
    examCode: 'ASMO-MATH-G01-2020-R1',
    topicName: 'Đếm Khối Lập Phương 3D Bị Che Khuất',
    questionText: 'Có tất cả bao nhiêu khối lập phương đơn vị trong mô hình 3 tầng?',
    wrongRatePct: 54,
    wrongAttemptsCount: 118,
    commonPitfall: 'Bỏ sót các khối lập phương ở tầng đáy bị che khuất hoàn toàn bởi các khối ở tầng 2 và tầng 3.',
  },
  {
    questionId: 'asmo-math-g2-2020-r1-q09',
    examCode: 'ASMO-MATH-G02-2020-R1',
    topicName: 'Bài Toán Que Diêm Tư Duy',
    questionText: 'Di chuyển đúng 1 que diêm để được phép tính đúng: 6 + 4 = 4.',
    wrongRatePct: 49,
    wrongAttemptsCount: 95,
    commonPitfall: 'Di chuyển 2 que thay vì 1 que, hoặc nhầm lẫn giữa số 0, 6, 8 và số 9 trong mã hóa que diêm LED.',
  },
  {
    questionId: 'asmo-math-g3-2021-r1-q12',
    examCode: 'ASMO-MATH-G03-2021-R1',
    topicName: 'Phân Số Diện Tích Hình Tô Màu',
    questionText: 'Tính tỉ số diện tích phần tô đậm so với toàn bộ hình vuông cạnh $a$.',
    wrongRatePct: 43,
    wrongAttemptsCount: 81,
    commonPitfall: 'Cộng dồn diện tích các hình tam giác phụ nhưng không trừ diện tích phần giao nhau ở tâm.',
  },
]
