import { defaultCheck, type CourseSeed } from '../types.js'

/** Full experiential path: meet AI → create comic → mini cinema */
export const courseComic: CourseSeed = {
  id: 'course-comic',
  title: 'Tạo truyện tranh AI',
  shortTitle: 'Truyện tranh',
  tagline: 'Từ ý tưởng → nhân vật → 4 khung truyện',
  description:
    'Khóa trải nghiệm 8–11 tuổi: hiểu AI qua thực hành tạo truyện tranh — ghép thẻ, kiểm tra kết quả, kể chuyện.',
  coverFrom: '#6d5efc',
  coverTo: '#3dbfff',
  accent: '#6d5efc',
  coverImage: '/assets/designer/hub/art-comic.jpeg',
  ageLabel: '8–11 tuổi',
  durationLabel: '~60–90 phút',
  productLabel: '1 truyện tranh + video mini',
  status: 'open',
  recommended: true,
  skills: [
    'Hiểu AI là công cụ',
    'Prompt bằng thẻ',
    'Kiểm tra kết quả AI',
    'Kể chuyện 4 khung',
  ],
  outcomes: [
    '1 truyện tranh 4 khung trong ba lô',
    '1 video mini kể chuyện (riêng tư)',
    'Biết AI có thể sai và cách chỉnh',
    'Huy hiệu + sao theo từng trạm',
  ],
  sortOrder: 1,
  quests: [
    {
      id: 'meet-mascot',
      order: 1,
      title: 'Gặp Robot Mực',
      skill: 'AI là công cụ giúp con sáng tạo',
      reward: 'Huy hiệu Người khám phá',
      duration: '5–8 phút',
      hook: 'Chào con! Mình là Mực Màu — cùng khám phá AI nhé.',
      accent: '#6d5efc',
      practiceKind: 'intro',
      // Demo CDN-style URLs — replace in production via teacher CMS / seed
      videoUrl:
        'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
      goals: ['Biết AI là gì', 'Biết con là người quyết định', 'Nhận huy hiệu'],
      concept:
        'AI (trí tuệ nhân tạo) là công cụ máy tính học từ ví dụ để giúp con tạo ảnh, câu chuyện.',
      example: 'Con mô tả “mèo đội mũ sao” → AI vẽ thử → con chọn ảnh đúng ý.',
      check: defaultCheck(
        'AI là gì với con?',
        [
          'Bạn thay thế con hoàn toàn',
          'Công cụ giúp con sáng tạo',
          'Chỉ để chơi game bạo lực',
        ],
        1,
      ),
    },
    {
      id: 'character',
      order: 2,
      title: 'Tạo nhân vật',
      skill: 'Chọn đặc điểm nhân vật rõ ràng',
      reward: 'Thẻ nhân vật vào ba lô',
      duration: '8–10 phút',
      hook: 'Tạo “bạn” để kể chuyện cùng con — như xưởng sáng tạo AIkid.',
      accent: '#3dbfff',
      practiceKind: 'character',
      videoUrl:
        'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
      goals: [
        'Chọn loại nhân vật',
        'Chọn tính cách',
        'Đặt biệt danh an toàn',
        'Lưu vào ba lô',
      ],
      concept:
        'Nhân vật cần: hình dáng (con vật / robot / …), tính cách, biệt danh vui — không dùng tên thật.',
      example: 'Mèo vũ trụ tò mò, muốn tìm cầu vồng.',
    },
    {
      id: 'style-pick',
      order: 3,
      title: 'Chọn phong cách vẽ',
      skill: 'Chọn art style trước khi AI vẽ',
      reward: 'Thẻ phong cách Soft Clay',
      duration: '6–8 phút',
      hook: 'Cùng phong cách xưởng AIkid: màu nước, clay, chibi… — không bóng nhựa AI!',
      accent: '#ff7b93',
      practiceKind: 'style',
      goals: [
        'Xem các thẻ style designer',
        'Chọn 1 phong cách yêu thích',
        'Hiểu style giúp AI vẽ đúng “cảm”',
      ],
      concept:
        'Phong cách (art style) = “giọng vẽ”. Clay/màu nước/chibi khác hẳn chrome nhựa bóng.',
      example: 'Chọn clay → nhân vật tròn, mềm, handmade.',
    },
    {
      id: 'world-build',
      order: 4,
      title: 'Chọn thế giới',
      skill: 'Bối cảnh giúp AI hiểu câu chuyện',
      reward: 'Phông nền thế giới',
      duration: '6–8 phút',
      hook: 'Câu chuyện xảy ra ở đâu?',
      accent: '#3ed9a0',
      practiceKind: 'chips',
      goals: ['Chọn nơi chốn', 'Thêm chi tiết an toàn', 'Hiểu bối cảnh'],
      concept: 'Bối cảnh = nơi + không khí. Càng rõ, AI càng vẽ đúng.',
      example: 'Hành tinh kẹo + bầu trời tím = vui và lạ.',
    },
    {
      id: 'plot',
      order: 5,
      title: 'Chọn sự cố vui',
      skill: 'Cốt truyện 3 nhịp: mở – sự cố – kết',
      reward: 'Dàn ý truyện',
      duration: '8–10 phút',
      hook: 'Truyện hay cần một “vấn đề” dễ thương.',
      accent: '#ffc94a',
      practiceKind: 'story',
      goals: ['Chọn mở đầu', 'Chọn sự cố', 'Chọn kết'],
      concept: '3 nhịp: bắt đầu → chuyện gì xảy ra → giải quyết vui.',
      example: 'Máy cầu vồng hỏng → hai bạn sửa → cầu vồng trở lại.',
    },
    {
      id: 'prompt-lab',
      order: 6,
      title: 'Phòng thí nghiệm Prompt',
      skill: 'Ghép thẻ mô tả để AI vẽ',
      reward: 'Ảnh do AI vẽ (mô phỏng)',
      duration: '10–12 phút',
      hook: 'Ghép thẻ → AI vẽ ảnh cho truyện.',
      accent: '#ff7b93',
      practiceKind: 'chips',
      goals: ['Đủ 5 thẻ', 'Xem câu mô tả', 'Tạo ảnh thử'],
      concept: 'Prompt = lời hướng dẫn cho AI. Thẻ giúp con viết rõ và an toàn.',
      example: 'mèo vũ trụ, nhảy múa, ở hành tinh kẹo, vui vẻ, truyện tranh.',
    },
    {
      id: 'detective',
      order: 7,
      title: 'Thám tử AI',
      skill: 'AI có thể sai — con kiểm tra',
      reward: 'Kính thám tử',
      duration: '8–10 phút',
      hook: 'Tìm chi tiết AI vẽ lệch ý!',
      accent: '#6d5efc',
      practiceKind: 'detective',
      goals: ['So sánh 2 ảnh', 'Chọn ảnh đúng ý', 'Giải thích vì sao'],
      concept: 'AI không hiểu như người. Con phải kiểm tra kết quả.',
      example: 'Con muốn mèo — AI vẽ chó? Chọn lại hoặc chỉnh prompt.',
      check: defaultCheck(
        'Vì sao con cần kiểm tra ảnh AI?',
        ['Vì AI luôn đúng 100%', 'Vì AI có thể vẽ sai ý', 'Vì không cần xem'],
        1,
      ),
    },
    {
      id: 'comic',
      order: 8,
      title: 'Làm truyện 4 khung',
      skill: 'Ghép ảnh + lời thoại thành truyện',
      reward: 'Truyện tranh trong portfolio',
      duration: '12–15 phút',
      hook: 'Ghép 4 khung thành một câu chuyện!',
      accent: '#3dbfff',
      practiceKind: 'comic',
      goals: ['Điền 4 khung', 'Thêm lời thoại ngắn', 'Lưu truyện'],
      concept: 'Mỗi khung = 1 nhịp: mở, sự cố, hành động, kết.',
      example: 'Khung 1 chào mừng → khung 2 sự cố → khung 3 sửa → khung 4 vui.',
    },
    {
      id: 'cinema',
      order: 9,
      title: 'Mini rạp phim',
      skill: 'Biến truyện thành video kể chuyện',
      reward: 'Video mini + sao khóa học',
      duration: '10–12 phút',
      hook: 'Cho gia đình xem câu chuyện của con!',
      accent: '#3ed9a0',
      practiceKind: 'video',
      goals: ['Sắp cảnh', 'Thêm lời kể', 'Xuất bản riêng tư'],
      concept: 'Video = từng khung + thời gian + lời kể ngắn.',
      example: 'Mỗi cảnh 3–4 giây, lời kể 1 câu.',
    },
  ],
}
