import { defaultCheck, type CourseSeed } from '../types.js'

/** Complete robot design course (open) */
export const courseRobot: CourseSeed = {
  id: 'course-robot',
  title: 'Robot sáng tạo',
  shortTitle: 'Robot',
  tagline: 'Thiết kế robot vui + nhiệm vụ AI',
  description:
    'Hiểu “máy học từ ví dụ” qua thiết kế robot tưởng tượng: bộ phận, nhiệm vụ, quy tắc an toàn.',
  coverFrom: '#3dbfff',
  coverTo: '#6d5efc',
  accent: '#3dbfff',
  coverImage: '/assets/designer/lobby/mascot.png',
  ageLabel: '8–11 tuổi',
  durationLabel: '~35 phút',
  productLabel: '1 thẻ robot + badge',
  status: 'open',
  recommended: false,
  skills: [
    'Chọn bộ phận robot',
    'Gán nhiệm vụ',
    'Quy tắc an toàn robot',
    'Giải thích vì sao AI cần dữ liệu',
  ],
  outcomes: [
    'Thẻ robot + nhiệm vụ trong ba lô',
    'Hiểu máy học cần ví dụ đúng/sai',
    'Sao Kỹ sư nhí',
  ],
  sortOrder: 4,
  quests: [
    {
      id: 'bot-parts',
      order: 1,
      title: 'Chọn bộ phận robot',
      skill: 'Robot = cảm biến + “não” + hành động',
      reward: 'Kit bộ phận',
      duration: '8 phút',
      hook: 'Mắt camera, tay kẹp, hay bánh xe?',
      accent: '#3dbfff',
      practiceKind: 'character',
      goals: ['Chọn 3 bộ phận', 'Đặt tên robot', 'Lưu thẻ'],
      concept: 'Cảm biến nhận thông tin → não quyết định → cơ quan hành động.',
      example: 'Mắt thấy bóng → não chọn đá → chân sút.',
      check: defaultCheck(
        '“Não” robot gần giống phần nào của AI?',
        ['Bánh xe', 'Mô hình học từ ví dụ để quyết định', 'Màu sơn'],
        1,
      ),
    },
    {
      id: 'bot-job',
      order: 2,
      title: 'Robot làm việc gì?',
      skill: 'Gắn nhiệm vụ vui và rõ',
      reward: 'Thẻ nhiệm vụ',
      duration: '8 phút',
      hook: 'Dọn phòng? Kể chuyện? Trồng cây?',
      accent: '#ffc94a',
      practiceKind: 'chips',
      goals: ['Chọn nhiệm vụ', 'Nói rõ đầu vào', 'Nói rõ đầu ra'],
      concept: 'AI cần mục tiêu rõ: nhận gì → làm gì → ra gì.',
      example: 'Nhận ảnh đồ chơi lộn xộn → sắp theo màu → phòng gọn.',
    },
    {
      id: 'bot-train',
      order: 3,
      title: 'Dạy robot bằng ví dụ',
      skill: 'Máy học cần ví dụ đúng và sai',
      reward: 'Huy hiệu Huấn luyện viên',
      duration: '10 phút',
      hook: 'Cho robot xem 3 ví dụ “đúng” và 1 “sai”.',
      accent: '#6d5efc',
      practiceKind: 'detective',
      goals: ['Chọn ví dụ tốt', 'Loại ví dụ xấu', 'Hiểu bias đơn giản'],
      concept: 'Nếu chỉ dạy một kiểu, robot dễ sai với kiểu khác.',
      example: 'Chỉ dạy mèo trắng → gặp mèo đen có thể nhầm.',
      check: defaultCheck(
        'Nếu chỉ dạy robot bằng 1 kiểu ví dụ?',
        ['Robot luôn hoàn hảo', 'Robot dễ sai với trường hợp mới', 'Không cần ví dụ'],
        1,
      ),
    },
    {
      id: 'bot-safe',
      order: 4,
      title: 'Robot an toàn',
      skill: 'Quy tắc an toàn cho máy thông minh',
      reward: 'Sao Kỹ sư nhí',
      duration: '8 phút',
      hook: 'Robot không được làm gì?',
      accent: '#3ed9a0',
      practiceKind: 'intro',
      goals: ['3 quy tắc an toàn', 'Ví dụ thực tế', 'Nhận badge'],
      concept: 'Không làm hại, không lấy bí mật, luôn có người lớn giám sát.',
      example: 'Robot nhà không mở cửa cho người lạ.',
    },
  ],
}
