import { defaultCheck, type CourseSeed } from '../types.js'

export const courseSafety: CourseSeed = {
  id: 'course-safety',
  title: 'An toàn với AI',
  shortTitle: 'An toàn',
  tagline: 'Bí mật, kiểm tra, hỏi người lớn',
  description:
    'Mini-course bảo vệ thông tin và tư duy phản biện với AI — bắt buộc trước khi chia sẻ sáng tạo.',
  coverFrom: '#3ed9a0',
  coverTo: '#6d5efc',
  accent: '#3ed9a0',
  coverImage: '/assets/designer/lobby/card_diary.jpeg',
  ageLabel: '8–11 tuổi',
  durationLabel: '~25 phút',
  productLabel: 'Huy hiệu Bảo vệ',
  status: 'open',
  recommended: true,
  skills: ['Không chia sẻ PII', 'Nhận AI sai', 'Hỏi người lớn'],
  outcomes: [
    'Huy hiệu Bảo vệ sáng tạo',
    '3 quy tắc vàng khi dùng AI',
    'Biết khi nào phải hỏi ba mẹ / thầy cô',
  ],
  sortOrder: 2,
  quests: [
    {
      id: 'safe-hello',
      order: 1,
      title: 'AI và bí mật',
      skill: 'Không chia sẻ thông tin cá nhân',
      reward: 'Khiên bảo vệ',
      duration: '6 phút',
      hook: 'Những gì không nên kể cho AI?',
      accent: '#6d5efc',
      practiceKind: 'intro',
      goals: ['Nhận biết PII', 'Chọn biệt danh', 'Giữ an toàn'],
      concept: 'Không đưa email, số điện thoại, địa chỉ, tên trường thật.',
      example: 'Dùng “MèoSao” thay vì tên thật + lớp.',
      check: defaultCheck(
        'Con KHÔNG nên đưa gì cho AI?',
        ['Biệt danh vui', 'Số điện thoại thật', 'Tên nhân vật tưởng tượng'],
        1,
      ),
    },
    {
      id: 'safe-spot',
      order: 2,
      title: 'Tìm chi tiết lạ',
      skill: 'Nhận ra kết quả AI đáng ngờ',
      reward: 'Mắt thám tử',
      duration: '7 phút',
      hook: 'Luyện mắt tìm điểm lạ.',
      accent: '#ffc94a',
      practiceKind: 'detective',
      goals: ['Tìm điểm sai', 'Giải thích', 'Chọn an toàn'],
      concept: 'Nếu ảnh/câu lạ hoặc xin thông tin — dừng và hỏi người lớn.',
      example: 'AI xin số điện thoại? Không trả lời — báo ba mẹ.',
    },
    {
      id: 'safe-choice',
      order: 3,
      title: 'Chọn cách an toàn',
      skill: 'Ra quyết định đúng khi nghi ngờ',
      reward: 'Huy hiệu An toàn',
      duration: '6 phút',
      hook: 'Tình huống — con chọn gì?',
      accent: '#3ed9a0',
      practiceKind: 'intro',
      goals: ['Chọn hành động đúng', 'Biết hỏi người lớn', 'Hoàn thành'],
      concept: 'Khi không chắc — hỏi ba mẹ / thầy cô.',
      example: 'Không gửi ảnh khuôn mặt thật cho người lạ trên mạng.',
      check: defaultCheck(
        'Khi nghi ngờ, con nên?',
        ['Tự quyết một mình', 'Hỏi ba mẹ hoặc thầy cô', 'Chia sẻ ngay cho bạn bè'],
        1,
      ),
    },
    {
      id: 'safe-badge',
      order: 4,
      title: 'Huy hiệu bảo vệ',
      skill: 'Ôn lại quy tắc an toàn',
      reward: 'Huy hiệu Bảo vệ sáng tạo',
      duration: '5 phút',
      hook: 'Con đã sẵn sàng sáng tạo an toàn!',
      accent: '#ff7b93',
      practiceKind: 'intro',
      goals: ['Ôn 3 quy tắc', 'Nhận huy hiệu', 'Về bản đồ'],
      concept: '1) Không PII 2) Kiểm tra AI 3) Hỏi người lớn khi nghi.',
      example: 'Ba quy tắc vàng của Nhà sáng tạo nhí.',
    },
  ],
}
