import { defaultCheck, type CourseSeed } from '../types.js'

/** Complete voice storytelling course (now open, not stub) */
export const courseVoice: CourseSeed = {
  id: 'course-voice',
  title: 'Giọng kể chuyện',
  shortTitle: 'Giọng kể',
  tagline: 'Ý tưởng → giọng kể → cảnh + lời',
  description:
    'Học cách viết lời kể ngắn, chọn giọng (mô phỏng), ghép với cảnh — hiểu AI hỗ trợ âm thanh như thế nào.',
  coverFrom: '#ffc94a',
  coverTo: '#ff7b93',
  accent: '#ffc94a',
  coverImage: '/assets/designer/lobby/art-video.jpeg',
  ageLabel: '8–11 tuổi',
  durationLabel: '~40 phút',
  productLabel: '1 video kể chuyện mini',
  status: 'open',
  recommended: false,
  skills: ['Viết lời kể ngắn', 'Chọn giọng', 'Ghép cảnh + lời', 'Trình diễn an toàn'],
  outcomes: [
    '1 video kể chuyện mini',
    'Biết viết lời kể 3 câu an toàn',
    'Sao diễn viên nhí trong ba lô',
  ],
  sortOrder: 3,
  quests: [
    {
      id: 'voice-idea',
      order: 1,
      title: 'Ý tưởng lời kể',
      skill: 'Viết 3 câu chuyện ngắn an toàn',
      reward: 'Sổ ý tưởng',
      duration: '8 phút',
      hook: 'Mỗi câu chuyện chỉ 3 câu thôi!',
      accent: '#ffc94a',
      practiceKind: 'story',
      goals: ['Chọn chủ đề', 'Viết 3 câu', 'Giữ an toàn'],
      concept: 'Lời kể ngắn: ai – làm gì – kết quả vui.',
      example: 'Mèo bay lên mây. Gặp cầu vồng gãy. Hai bạn sửa xong.',
      check: defaultCheck(
        'Lời kể tốt cho 8–11 tuổi nên?',
        ['Rất dài và dùng tên trường thật', 'Ngắn, vui, không PII', 'Chỉ copy nguyên văn từ AI'],
        1,
      ),
    },
    {
      id: 'voice-pick',
      order: 2,
      title: 'Chọn giọng kể',
      skill: 'Nghe thử và chọn giọng phù hợp',
      reward: 'Micro ma thuật',
      duration: '7 phút',
      hook: 'Giọng vui, giọng êm, hay giọng phiêu lưu?',
      accent: '#3dbfff',
      practiceKind: 'intro',
      goals: ['Nghe 3 mẫu', 'Chọn 1 giọng', 'Giải thích vì sao'],
      concept: 'AI có thể bắt chước giọng — con vẫn là đạo diễn.',
      example: 'Truyện vui → giọng tươi; truyện đêm → giọng êm.',
    },
    {
      id: 'voice-scene',
      order: 3,
      title: 'Ghép cảnh + lời',
      skill: 'Mỗi cảnh một câu kể',
      reward: 'Storyboard âm thanh',
      duration: '10 phút',
      hook: '4 cảnh = 4 câu kể.',
      accent: '#6d5efc',
      practiceKind: 'comic',
      goals: ['Gắn lời vào cảnh', 'Không trùng lặp', 'Lưu dàn ý'],
      concept: 'Đồng bộ hình + lời giúp người xem hiểu chuyện.',
      example: 'Cảnh 1 chào → cảnh 2 sự cố → cảnh 3 hành động → cảnh 4 kết.',
    },
    {
      id: 'voice-show',
      order: 4,
      title: 'Trình diễn mini',
      skill: 'Xem trước video kể chuyện',
      reward: 'Sao diễn viên nhí',
      duration: '10 phút',
      hook: 'Xuất bản riêng tư — xin ba/mẹ nếu muốn chia sẻ.',
      accent: '#3ed9a0',
      practiceKind: 'video',
      goals: ['Xem trước', 'Chỉnh 1 chỗ', 'Lưu portfolio'],
      concept: 'Sáng tạo mặc định riêng tư; chia sẻ cần người lớn đồng ý.',
      example: 'Bấm “Xin ba/mẹ chia sẻ” trong ba lô.',
      check: defaultCheck(
        'Trước khi chia sẻ video, con nên?',
        ['Đăng công khai ngay', 'Xin ba/mẹ duyệt', 'Gửi cho người lạ'],
        1,
      ),
    },
  ],
}
